### ISSUE TITLE
Missing info in Documentation

### ISSUE THREAD

**Issue by dejan-mladenovski** [netceteragroup/girders#49]
Hi Girders Team, 

I noticed in the documentation there are a couple of things missing:
* In the documentation the `Release Notes` menu item is going to 404
* Under `Contributing`, the links to `small team` and `Girders team` are also 404s
* In the `Getting started` section, is it really relevant in the POM example that the groupId is `com.netcetera...`? 
* Also under `Contributing`, it is good that `Girders is open for contribution from everybody`, but I think some rules of engagement are missing; from where to checkout a branch for contribution, naming conventions,...
* Some rules for opening an Issue; what is the issue format, minimum info required,...

**Comment by MarijaPopova** [comment]
Hi Dejan is this okay with you ? 
![Screenshot 2023-04-13 at 15 48 11](https://user-images.githubusercontent.com/12382018/231780233-52e53bbf-afcf-4a39-9a15-460954819900.png)

i fixed all the other remarks that you reported but i am not sure what do you think about the rules of engagement :)

**Comment by dejan-mladenovski** [comment]
@MarijaPopova it is good. 

For rules of engagement, I mean some guidelines for Code of Conduct, template for reporting issues. Take a look at the Spring Boot repo for example: https://github.com/spring-projects/spring-boot/issues

At the top there is a link to "contributing guidelines". In there is a section Code of Conduct. Maybe not go into such details, but some small info is appreciated. 

For bug/feature report, you have templates available. For example, it is helpful when opening a bug issue, to include the version that is affected, how to replicate the issue, details of the bug etc. You can take a look at the Angular repo template here: https://github.com/angular/angular/issues/new/choose 

All of these features are GitHub enabled, so you can configure them.
