### ISSUE TITLE
Spring-ws 4.0.4 version in Girders 6.1.0 does not have support for Apache Http Client 5.0

### ISSUE THREAD

**Issue by GiannisGl** [netceteragroup/girders#66]
Girders 6.1.0 contains the 4.0.4 version of the spring-ws dependencies. Unfortunately this does not have support for Apache Http Client 5.0. The newest 4.0.5 version (released 22.06.23) has the required support though. See https://github.com/spring-projects/spring-ws/issues/1164.
So for projects using Web Services this dependency need to be upgraded manually currently.
For the next Girders version please consider upgrading this dependency. 
Thank you

**Comment by MarijaPopova** [comment]
Hi @GiannisGl this will be fixed now with the next version of Girders EOW.

**Comment by MarijaPopova** [comment]
Fixed with the new release 6.2.0
